name: contract
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/hardhat
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run coverage
